[workspace]

[package]
name = "fuzz_tests"
version = "0.1.0"
description = "Created with Trident"
edition = "2021"

[dependencies]
borsh = "1.5.3"
rand = "0.8"

[dependencies.trident-fuzz]
version = "0.12.0"

[[bin]]
name = "fuzz_0"
path = "fuzz_0/test_fuzz.rs"
